---
deployment:
  tasks:
    - export DEPLOYPATH=/home/codemak/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp download.png $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
